# Generated by Django 3.2.5 on 2021-07-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('RegistrationDate', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pics')),
            ],
        ),
    ]
